version: 2
jobs:
  build_and_test:
    working_directory: ~/oya-project
    docker:
      - image: circleci/ruby:2.5-node-browsers
        environment:
          RAILS_ENV: test
    branches:
      ignore:
        - master
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: curl -O https://s3.eu-central-1.amazonaws.com/oyabinary/oya
      - run: chmod +x oya
      - run: ./oya run onPush

  deploy:
    working_directory: ~/oya-project
    docker:
      - image: circleci/ruby:2.5-node-browsers
        environment:
          RAILS_ENV: test
    branches:
      only:
        - master
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: curl -O https://s3.eu-central-1.amazonaws.com/oyabinary/oya
      - run: chmod +x oya
      - run: ./oya run onPush
      - run: ./oya run onMergeToMaster
