version: 2
jobs:
  build:
    working_directory: ~/oya-project
    docker:
      - image: circleci/ruby:2.5-node-browsers
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: curl -O https://s3.eu-central-1.amazonaws.com/oyabinary/oya
      - run: chmod +x oya

  test:
    working_directory: ~/oya-project
    docker:
      - image: circleci/ruby:2.5-node-browsers
        environment:
          RAILS_ENV: test

    steps:
      - checkout
      - run: ./oya run onPush

  deploy:
    working_directory: ~/oya-project
    docker:
      - image: circleci/ruby:2.5-node-browsers
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - run: ./oya run onMergeToMaster

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
